services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  ruby:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    stdin_open: true
    tty: true

volumes:
  redis-data:
    driver: local
